import { NextRequest, NextResponse } from 'next/server';
import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';

const SHEET_ID = '1jFSbwCRhA5XRcUAuka6aoWSOuV_FrnnAACggPB-Zhyc';
const SERVICE_ACCOUNT_EMAIL = process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL;

const SERVICE_ACCOUNT_PRIVATE_KEY =
  process.env.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY!.replace(/\\n/g, '\n');

export async function POST(req: NextRequest) {
  try {
    const body = await req.json(); // Отримуємо JSON з запиту

    const {
      fitnessGoal,
      gymFrequency,
      dietTracking,
      mealPlanning,
      mealChallenges,
      autoGeneratedMenu,
      payForService,
      preferredFormat,
      testVersion,
      contact,
    } = body; // Отримуємо всі відповіді

    const auth = new JWT({
      email: SERVICE_ACCOUNT_EMAIL,
      key: SERVICE_ACCOUNT_PRIVATE_KEY,
      scopes: ['https://www.googleapis.com/auth/spreadsheets'],
    });

    const doc = new GoogleSpreadsheet(SHEET_ID, auth);
    await doc.loadInfo();

    const sheet = doc.sheetsByIndex[0]; // Використовуємо перший аркуш
    await sheet.addRow({
      'Фітнес-ціль': fitnessGoal || '',
      'Частота тренувань': gymFrequency || '',
      'Як слідкує за харчуванням': dietTracking || '',
      'Як складає раціон': mealPlanning || '',
      'Труднощі з харчуванням': mealChallenges.join(', ') || '',
      'Чи цікаве автоматичне меню': autoGeneratedMenu || '',
      'Чи готовий платити': payForService || '',
      'Формат меню': preferredFormat || '',
      'Цікавість до тестування': testVersion || '',
      Контакт: contact || '',
    });

    return NextResponse.json(
      { message: 'Response saved successfully' },
      { status: 200 }
    );
  } catch (error) {
    console.error('Error saving response:', error);
    return NextResponse.json(
      { message: 'Error saving response', error },
      { status: 500 }
    );
  }
}
